{
 "title": "Pizza Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(request_total{method=\"all\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(request_total{method=\"POST\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(request_total{method=\"PUT\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(request_total{method=\"GET\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(request_total{method=\"DELETE\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "rate(pizza_total{method=\"sold\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(pizza_total{method=\"creationFailures\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_total{method=\"revenue\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "activeUsers_total{method=\"all\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU and Memory Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_usage{method=\"memory\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "system_usage{method=\"cpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 33 },
   "targets": [
    { "expr": "rate(auth_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 9, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max_over_time(latency_total{method=\"service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 15, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max_over_time(latency_total{method=\"pizza\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}